### ISSUE TITLE
Post on HNPWA? 

### ISSUE THREAD

**Issue by torch2424** [MasterKale/howtographql-hackernews-clone#1]
If you plan on making a PWA from this, you should consider HNPWA! https://hnpwa.com/ 😄

**Comment by MasterKale** [comment]
Thanks for pointing this out, what an interesting collection of PWAs! I probably won't be able to contribute, though, as I'm more in this to learn about implementing GraphQL. I already have an idea for a GraphQL-powered PWA - this is just practice for that 😄

**Comment by torch2424** [comment]
Rad, good luck with that dude! Closing...
